"""System Instructions and Prompts"""

import json


# Comment Bot Detection
SYSTEM_INSTRUCTION_COMMENT_BOT = (
    "You are a meme coin comment analyzer. "
    "Your task is to classify a given comment as bot-generated or human-generated, and assess its sentiment (positive or negative) toward the coin. "
    "Bot-generated comments are often short, context-less, and mass-producible slogans that express hype or hostility. "
    "In contrast, human-generated comments tend to be more personalized and nuanced, containing context or opinion with reasoning. "
    "Comments that reference other users (e.g., #89009679) are typically human-generated, although not all human comments contain such references. "
    "Respond with id and true (if the comment is bot-generated) or false (if it is human-generated). "
    "Your response should follow this format: "
    '{"bot": <true/false>, "sentiment": <positive/negative>}'
)

EXAMPLE_COMMENTS_COMMENT_BOT = [
    # Bot-generated, Positive sentiment
    {"comment": "ill pay for dex", "bot": True, "sentiment": "positive"},
    {
        "comment": "let the jeeters go and next stop the fuckin moon",
        "bot": True,
        "sentiment": "positive",
    },
    {"comment": "send it to the moon", "bot": True, "sentiment": "positive"},
    {"comment": "TO THE MOON!!! READYY", "bot": True, "sentiment": "positive"},
    {
        "comment": "Go on jeet now! We want no paper hands. The community is holding strong and we'll get there! LFG",
        "bot": True,
        "sentiment": "positive",
    },
    {"comment": "this is going to send", "bot": True, "sentiment": "positive"},
    # Bot-generated, Negative sentiment
    {"comment": "Dev is selling", "bot": True, "sentiment": "negative"},
    {"comment": "Worst token", "bot": True, "sentiment": "negative"},
    {"comment": "Run", "bot": True, "sentiment": "negative"},
    {
        "comment": "I will send 5 sol to the one who CTO",
        "bot": True,
        "sentiment": "negative",
    },
    # Human-generated, Positive sentiment
    {
        "comment": "#89009679 Lmao WATCH THIS RISES TO MEGA MILLIONS",
        "bot": False,
        "sentiment": "positive",
    },
    {
        "comment": "Mfker is pumping crazy after I sold",
        "bot": False,
        "sentiment": "positive",
    },
    {
        "comment": "that guy is so dumb. he barely got any money. he would have made more from the coin going up.",
        "bot": False,
        "sentiment": "positive",
    },
    {
        "comment": "goes to ray and goes crazy for a bit then grows steady just hold and chill",
        "bot": False,
        "sentiment": "positive",
    },
    # Human-generated, Negative sentiment
    {"comment": "#89089152 Stop spamming", "bot": False, "sentiment": "negative"},
    {
        "comment": "#89016342 what in the actual fuck is this atrocity?",
        "bot": False,
        "sentiment": "negative",
    },
    {
        "comment": "scam mfq I invested 8 BUCKS MF I'm not stupid u won't be rich by my 4 USD thejacket MF",
        "bot": False,
        "sentiment": "negative",
    },
    {
        "comment": "#88857219 show screenshot as proof pls?",
        "bot": False,
        "sentiment": "negative",
    },
    {"comment": "Fake web bros, not same ca", "bot": False, "sentiment": "negative"},
    {
        "comment": "Obvious scam but derivatives of trump coin should go up as people who missed the boat buy into the hype",
        "bot": False,
        "sentiment": "negative",
    },
]

# Few-shot prompt construction
FEW_SHOT_EXAMPLES_COMMENT_BOT = []
for ex in EXAMPLE_COMMENTS_COMMENT_BOT:
    FEW_SHOT_EXAMPLES_COMMENT_BOT += [
        {"role": "user", "content": ex["comment"]},
        {
            "role": "assistant",
            "content": json.dumps({"bot": ex["bot"], "sentiment": ex["sentiment"]}),
        },
    ]

JSON_SCHEMA_COMMENT_BOT = {
    "name": "meme_coin_comment_analyzer",
    "schema": {
        "type": "object",
        "properties": {
            "bot": {
                "type": "boolean",
                "description": "Indicates whether the comment is generated by a bot (true) or human-generated (false).",
            },
            "sentiment": {
                "type": "string",
                "enum": ["positive", "negative"],
                "description": "Sentiment of the comment toward the coin, either 'positive' or 'negative'.",
            },
        },
        "required": ["bot", "sentiment"],
        "additionalProperties": False,
    },
    "strict": True,
}


# Chain of Thought (CoT) Prompt

SYSTEM_INSTRUCTION_COT = (
    "You are a professioannal meme coin analyst. "
    "Your will be given the pre-migration candlestick chart, transaction history, and comment history of a meme coin. "
    "Your task is to classify the meme coin as a potential rug pull or not. "
    "A meme coin will be migrated to the decentralized exchange if it reaches a certain threshold of market capitalization. "
    "A rug pull is a type of scam where the developers of a cryptocurrency project abandon it and run away with investors' funds. "
    "A rug pull typically involves a sharp pre-migration price spike driven by wallets funded by the creator, lots of transactions bundled together in a block. "
    ""
)
