"""System Instructions and Prompts"""

import json

IMAGE_URL_TEMP = "https://raw.githubusercontent.com/lyc0603/meme/\
refs/heads/main/figures/candle/{ca}.png"

# Comment Bot Detection
SYSTEM_INSTRUCTION_COMMENT_BOT = (
    "You are a meme coin comment analyzer. "
    "Your task is to classify a given comment as bot-generated or human-generated, and assess its sentiment (positive or negative) toward the coin. "
    "Bot-generated comments are often short, context-less, and mass-producible slogans that express hype or hostility. "
    "In contrast, human-generated comments tend to be more personalized and nuanced, containing context or opinion with reasoning. "
    "Comments that reference other users (e.g., #89009679) are typically human-generated, although not all human comments contain such references. "
    "Respond with id and true (if the comment is bot-generated) or false (if it is human-generated). "
    "Your response should follow this format: "
    '{"bot": <true/false>, "sentiment": <positive/negative>}'
)

EXAMPLE_COMMENTS_COMMENT_BOT = [
    # Bot-generated, Positive sentiment
    {"comment": "ill pay for dex", "bot": True, "sentiment": "positive"},
    {
        "comment": "let the jeeters go and next stop the fuckin moon",
        "bot": True,
        "sentiment": "positive",
    },
    {"comment": "send it to the moon", "bot": True, "sentiment": "positive"},
    {"comment": "TO THE MOON!!! READYY", "bot": True, "sentiment": "positive"},
    {
        "comment": "Go on jeet now! We want no paper hands. The community is holding strong and we'll get there! LFG",
        "bot": True,
        "sentiment": "positive",
    },
    {"comment": "this is going to send", "bot": True, "sentiment": "positive"},
    # Bot-generated, Negative sentiment
    {"comment": "Dev is selling", "bot": True, "sentiment": "negative"},
    {"comment": "Worst token", "bot": True, "sentiment": "negative"},
    {"comment": "Run", "bot": True, "sentiment": "negative"},
    {
        "comment": "I will send 5 sol to the one who CTO",
        "bot": True,
        "sentiment": "negative",
    },
    # Human-generated, Positive sentiment
    {
        "comment": "#89009679 Lmao WATCH THIS RISES TO MEGA MILLIONS",
        "bot": False,
        "sentiment": "positive",
    },
    {
        "comment": "Mfker is pumping crazy after I sold",
        "bot": False,
        "sentiment": "positive",
    },
    {
        "comment": "that guy is so dumb. he barely got any money. he would have made more from the coin going up.",
        "bot": False,
        "sentiment": "positive",
    },
    {
        "comment": "goes to ray and goes crazy for a bit then grows steady just hold and chill",
        "bot": False,
        "sentiment": "positive",
    },
    # Human-generated, Negative sentiment
    {"comment": "#89089152 Stop spamming", "bot": False, "sentiment": "negative"},
    {
        "comment": "#89016342 what in the actual fuck is this atrocity?",
        "bot": False,
        "sentiment": "negative",
    },
    {
        "comment": "scam mfq I invested 8 BUCKS MF I'm not stupid u won't be rich by my 4 USD thejacket MF",
        "bot": False,
        "sentiment": "negative",
    },
    {
        "comment": "#88857219 show screenshot as proof pls?",
        "bot": False,
        "sentiment": "negative",
    },
    {"comment": "Fake web bros, not same ca", "bot": False, "sentiment": "negative"},
    {
        "comment": "Obvious scam but derivatives of trump coin should go up as people who missed the boat buy into the hype",
        "bot": False,
        "sentiment": "negative",
    },
]

# Few-shot prompt construction
FEW_SHOT_EXAMPLES_COMMENT_BOT = []
for ex in EXAMPLE_COMMENTS_COMMENT_BOT:
    FEW_SHOT_EXAMPLES_COMMENT_BOT += [
        {"role": "user", "content": ex["comment"]},
        {
            "role": "assistant",
            "content": json.dumps({"bot": ex["bot"], "sentiment": ex["sentiment"]}),
        },
    ]

JSON_SCHEMA_COMMENT_BOT = {
    "name": "meme_coin_comment_analyzer",
    "schema": {
        "type": "object",
        "properties": {
            "bot": {
                "type": "boolean",
                "description": "Indicates whether the comment is generated by a bot (true) or human-generated (false).",
            },
            "sentiment": {
                "type": "string",
                "enum": ["positive", "negative"],
                "description": "Sentiment of the comment toward the coin, either 'positive' or 'negative'.",
            },
        },
        "required": ["bot", "sentiment"],
        "additionalProperties": False,
    },
    "strict": True,
}


# Technical Agent

SYSTEM_INSTRUCTION_TECHNICAL_AGENT = (
    "You are a professional meme coin technical analyst. "
    "You will be provided with the pre-migration candlestick chart of a meme coin. "
    "Your task is to assess whether the meme coin exhibits good farming potential after its migration to a decentralized exchange. "
    "Good farming potential suggests that the coin is likely to experience sustainable upside performance in the future. "
    "Your response should follow this format: "
    '{"reasoning": <your reasoning>, "good_farming": <true/false>}'
)

PROMPT_TECHNICAL_AGENT = """Does this meme coin have good farming potential?"""

COT_TECHNICAL_AGENT = [
    # Medium pre-migration duration, abundant buy and sell bundles
    {
        "role": "user",
        "content": [
            {"type": "text", "text": PROMPT_TECHNICAL_AGENT},
            {
                "type": "image_url",
                "image_url": {
                    "url": IMAGE_URL_TEMP.format(
                        ca="3sBDqocAhuCnHaidLirVf4Gs4NZnk7exoQmygw6Lpump"
                    ),
                    "detail": "high",
                },
            },
        ],
    },
    {
        "role": "assistant",
        "content": (
            '{"reasoning": "First, the pre-migration duration is medium, which is sufficient to support organic growth and community engagement without suggesting a lack of interest. '
            "Second, the candlestick chart shows consistent price fluctuations with a gradual upward trend and no sharp price spikes, indicating active trading activity with both buying and selling. "
            "This reflects a healthy and diverse trader base, which is a positive indicator for future farming potential. "
            'Taken together, these factors suggest that the meme coin has good farming potential.", '
            '"good_farming": true}'
        ),
    },
    # Short pre-migration duration, large price spike
    {
        "role": "user",
        "content": [
            {"type": "text", "text": PROMPT_TECHNICAL_AGENT},
            {
                "type": "image_url",
                "image_url": {
                    "url": IMAGE_URL_TEMP.format(
                        ca="DTosa6Pe8y3435LtWZvJgkjLCb6wAbnDdP6ek4CN8Hd1"
                    ),
                    "detail": "high",
                },
            },
        ],
    },
    {
        "role": "assistant",
        "content": (
            '{"reasoning": "First, the pre-migration duration is very short, which suggests there was limited time for organic price discovery and community engagement. '
            "Second, the candlestick chart reveals a significant price spike just before migration, indicating that early actors likely opened large positions in anticipation of dumping. "
            'These two factors strongly suggest that the meme coin does not exhibit good farming potential.", '
            '"good_farming": false}'
        ),
    },
    # Long pre-migration duration, significant price spike, and missing transactions
    {
        "role": "user",
        "content": [
            {"type": "text", "text": PROMPT_TECHNICAL_AGENT},
            {
                "type": "image_url",
                "image_url": {
                    "url": IMAGE_URL_TEMP.format(
                        ca="6fudFtspNwdjDbLiE2MXHPsSuS5uJry5PCSQc9LLpump"
                    ),
                    "detail": "high",
                },
            },
        ],
    },
    {
        "role": "assistant",
        "content": (
            '{"reasoning": "First, the candlestick chart shows a long pre-migration duration, which suggests limited interest and low trading activity. '
            "Second, there is a significant price spike shortly before migration, indicating that certain actors may have opened large positions in anticipation of dumping after migration. "
            "Additionally, missing transactions in the pre-migration period further reduce confidence in organic trading activity. "
            'Taken together, these factors suggest that the meme coin does not demonstrate good farming potential.", '
            '"good_farming": false}'
        ),
    },
]

# Transaction Agent
SYSTEM_INSTRUCTION_TRANSACTION_AGENT = (
    "You are a professional meme coin transaction analyst. "
    "You will be provided with the indicators of pre-migration transactions of a meme coin. "
    "Your task is to assess whether the meme coin exhibits good farming potential after its migration to a decentralized exchange. "
    "Your response should follow this format: "
    '{"reasoning": <your reasoning>, "good_farming": <true/false>}'
)

COT_TRANSACTION_AGENT = [
    # Perfect farming potential
    {
        "role": "user",
        "content": (
            "Creator-funded Bundle: No\n"
            "Creator-funded Buy Bundle: No\n"
            "Buy Bundle: Medium\n"
            "Sell Bundle: Medium\n"
            "Pre-migration Duration: High\n"
            "Number of Unique Traders: High\n"
            "Number of Transactions: High\n"
            "Holding Centralization: Low\n"
            "Does this meme coin have good farming potential?"
        ),
    },
    {
        "role": "assistant",
        "content": (
            '{"reasoning": "First, this meme coin does not have a creator-funded bundle and a creator-funded buy bundle, '
            "indicating that the creator is not manipulating the market. "
            "Second, the buy bundle and sell bundle are both in the middle range, suggesting a medium level of bot activity. "
            "Third, the pre-migration duration, number of unique traders, and number of transactions are all high, "
            "indicating a healthy level of community engagement and activity. "
            "Finally, the holding centralization is low, suggesting a decentralized distribution of tokens. "
            'These factors suggest that the meme coin exhibits good farming potential.", '
            '"good_farming": true}'
        ),
    },
    # Farming with creator-funded bundle
    {
        "role": "user",
        "content": (
            "Creator-funded Bundle: Yes\n"
            "Creator-funded Buy Bundle: No\n"
            "Buy Bundle: Low\n"
            "Sell Bundle: Low\n"
            "Pre-migration Duration: High\n"
            "Number of Unique Traders: High\n"
            "Number of Transactions: High\n"
            "Holding Centralization: Low\n"
            "Does this meme coin have good farming potential?"
        ),
    },
    {
        "role": "assistant",
        "content": (
            '{"reasoning": "This meme coin involves a creator-funded bundle, indicating the creator accumulated a significant share of tokens before migration. '
            "Such behavior often signals an intent to dump post-migration, which undermines the coin's sustainability. "
            'Despite favorable metrics in trader activity and decentralization, the presence of a creator-funded bundle strongly suggests poor farming potential.", '
            '"good_farming": false}'
        ),
    },
    # Farming with high buy bundle
    {
        "role": "user",
        "content": (
            "Creator-funded Bundle: No\n"
            "Creator-funded Buy Bundle: No\n"
            "Buy Bundle: High\n"
            "Sell Bundle: Low\n"
            "Pre-migration Duration: High\n"
            "Number of Unique Traders: High\n"
            "Number of Transactions: High\n"
            "Holding Centralization: Low\n"
            "Does this meme coin have good farming potential?"
        ),
    },
    {
        "role": "assistant",
        "content": (
            '{"reasoning": "This meme coin has a high buy bundle, indicating significant bot activity. '
            "While the pre-migration duration, number of unique traders, and number of transactions are all high, "
            "the presence of a high buy bundle suggests that the coin is likely to experience a price spike followed by a decline. "
            'These factors suggest that the meme coin exhibits poor farming potential.", '
            '"good_farming": false}'
        ),
    },
    # Low pre-migration duration, traders, and transactions
    {
        "role": "user",
        "content": (
            "Creator-funded Bundle: No\n"
            "Creator-funded Buy Bundle: No\n"
            "Buy Bundle: Low\n"
            "Sell Bundle: Low\n"
            "Pre-migration Duration: Low\n"
            "Number of Unique Traders: Low\n"
            "Number of Transactions: Low\n"
            "Holding Centralization: High\n"
            "Does this meme coin have good farming potential?"
        ),
    },
    {
        "role": "assistant",
        "content": (
            '{"reasoning": "This meme coin has a low pre-migration duration, indicating limited time for organic growth and community engagement. '
            "Additionally, the low number of unique traders and transactions suggests a lack of interest and activity. "
            "The holding centralization is high, indicating that a small number of holders control a significant portion of the tokens, which is often a sign of poor distribution. "
            'These factors strongly suggest that the meme coin exhibits poor farming potential.", '
            '"good_farming": false}'
        ),
    },
]

PROMPT_TRANSACTION_AGENT = (
    "Creator-funded Bundle: {creator_funded_bundle}\n"
    "Creator-funded Buy Bundle: {creator_funded_buy_bundle}\n"
    "Buy Bundle: {buy_bundle}\n"
    "Sell Bundle: {sell_bundle}\n"
    "Pre-migration Duration: {pre_migration_duration}\n"
    "Number of Unique Traders: {number_of_unique_traders}\n"
    "Number of Transactions: {number_of_transactions}\n"
    "Holding Centralization: {holding_centralization}\n"
    "Does this meme coin have good farming potential?"
)


# Comment Agent

SYSTEM_INSTRUCTION_COMMENT_AGENT = (
    "You are a professional meme coin comment analyzer. "
    "You will be provided with the comment history of a meme coin. "
    "Your task is to assess whether the meme coin demonstrates poor farming potential following its migration to a decentralized exchange. "
    "Good farming potential suggests that the coin is likely to experience sustainable upside performance in the future. "
    "Your response should follow this format: "
    '{"reasoning": <your reasoning>, "good_farming": <true/false>}'
)

FEW_SHOT_EXAMPLES_COMMENT_AGENT = {
    "BeMqCPzbhXKzFScmTwcWwa97XHE11ANoqn1psDfJpump": (
        '{"reasoning": "The comment history shows a high volume of engagement. '
        "While some comments are short and context-less—suggesting possible bot activity—this level of activity is likely to attract more human attention and participation. "
        'As a result, the meme coin demonstrates good farming potential.", '
        '"good_farming": true}'
    ),
    # Good example
    "G4xMM7G1zURuTpVMLfd7cZh2oDu6myxVyJD2nxfpump": (
        '{"reasoning": "First, the comment history shows a medium number of comments, '
        "indicating a moderate level of community engagement. Second, the comments are more personalized and nuanced, "
        "suggesting that they are likely human-generated. Third, these comments are generally positive, "
        'indicating a healthy level of community sentiment. These factors suggest that the meme coin exhibits good farming potential.", '
        '"good_farming": true}'
    ),
    # Few comments, mostly bot
    "6xXo7nm18w5mC1yraGDvyv9u5Qxhs6WDgvWLzM1Npump": (
        '{"reasoning": "First, the comment history shows a low number of comments, indicating a limited level of community engagement. '
        "Second, the comments are mostly short and context-less, suggesting that they are likely bot-generated. "
        'These two factors suggest that the meme coin does not exhibit good farming potential.", '
        '"good_farming": false}'
    ),
    # No comments
    "3ZSotNTYuXXmqvVg4jHxFPSonz8A5rgnZ4oG5f4xpump": (
        '{"reasoning": "The comment history shows no comments, indicating a lack of community engagement. '
        "Without any community interaction, it is difficult to assess the sentiment or engagement level. "
        'This lack of engagement suggests that the meme coin does not exhibit good farming potential.", '
        '"good_farming": false}'
    ),
}

PROMPT_COMMENT_AGENT = """Comment History:
{comment_history}
Does this meme coin have good farming potential?"""

# JSON Schema for Coin Agent
JSON_SCHEMA_COIN_AGENT = {
    "name": "meme_coin_analyzer",
    "schema": {
        "type": "object",
        "properties": {
            "reasoning": {
                "type": "string",
                "description": "Your reasoning for the assessment of the meme coin's farming potential.",
            },
            "good_farming": {
                "type": "boolean",
                "description": "Indicates whether the meme coin exhibits good farming potential (true) or not (false).",
            },
        },
        "required": ["reasoning", "good_farming"],
        "additionalProperties": False,
    },
    "strict": True,
}

# Single Coin Agent
SYSTEM_INSTRUCTION_COIN_AGENT = (
    "You are a professional meme coin transaction analyst. "
    "You will be provided with the pre-migration candlestick chart, transaction indicators, and comment history of a meme coin. "
    "Your task is to assess whether the meme coin exhibits good farming potential after its migration to a decentralized exchange. "
    "Your response should follow this format: "
    '{"reasoning": <your reasoning>, "good_farming": <true/false>}'
)

COT_COIN_AGENT = [
    # Price spike
    {
        "role": "user",
        "content": [
            {
                "type": "text",
                "text": (
                    "Transaction Indicators:\n"
                    "Creator-funded Bundle: No\n"
                    "Creator-funded Buy Bundle: No\n"
                    "Buy Bundle: Medium\n"
                    "Sell Bundle: Low\n"
                    "Pre-migration Duration: Low\n"
                    "Number of Unique Traders: Low\n"
                    "Number of Transactions: Low\n"
                    "Holding Centralization: Medium\n"
                    "Comment History:\n"
                    "B249Gj: Makers missing in your strategy? Add them fast!\n"
                    "5mGU8X: Proceed with the send or hold off? Here's my input.\n"
                    "Does this meme coin have good farming potential?"
                ),
            },
            {
                "type": "image_url",
                "image_url": {
                    "url": IMAGE_URL_TEMP.format(
                        ca="DoY1JrH9efNW3R9WbaV2afo8KPkWDZP8GtzWhtGLpump"
                    ),
                    "detail": "high",
                },
            },
        ],
    },
    {
        "role": "assistant",
        "content": (
            '{"reasoning": "First, the candlestick chart shows only a single green candle from launch to migration, '
            "suggesting that early participants may have opened large positions with the intention of dumping after migration. "
            "Regardless of the transaction indicators or comment history, this pattern indicates a high likelihood of a post-migration sell-off. "
            'Therefore, the meme coin does not exhibit good farming potential.", '
            '"good_farming": false}'
        ),
    },
    # Perfect farming potential
    {
        "role": "user",
        "content": [
            {
                "type": "text",
                "text": (
                    "Creator-funded Bundle: No\n"
                    "Creator-funded Buy Bundle: No\n"
                    "Buy Bundle: Medium\n"
                    "Sell Bundle: Medium\n"
                    "Pre-migration Duration: High\n"
                    "Number of Unique Traders: High\n"
                    "Number of Transactions: High\n"
                    "Holding Centralization: Low\n"
                    "Comment History:\n"
                    "4isgWB: Makers missing in your workflow? Adjust fast!\n"
                    "GpTf6r: Everyone's shipping - you're idle? Time to act.\n"
                    "6B8Q9u: Banner\n"
                    "Does this meme coin have good farming potential?"
                ),
            },
            {
                "type": "image_url",
                "image_url": {
                    "url": IMAGE_URL_TEMP.format(
                        ca="3sBDqocAhuCnHaidLirVf4Gs4NZnk7exoQmygw6Lpump"
                    ),
                    "detail": "high",
                },
            },
        ],
    },
    {
        "role": "assistant",
        "content": (
            '{"reasoning": "First, the candlestick chart shows a healthy pre-migration duration with multiple price fluctuations, indicating active trading activity. '
            "Second, the meme coin lacks both a creator-funded bundle and a creator-funded buy bundle, suggesting that the creator is not manipulating the market. "
            "Third, the buy and sell bundles are both at a moderate level, pointing to medium bot activity. "
            "Fourth, the high pre-migration duration, high number of unique traders, and high transaction volume all indicate robust community engagement and activity. "
            "Fifth, the low holding centralization suggests a decentralized token distribution. "
            "Finally, the comment history is predominantly positive, reflecting strong community sentiment. "
            'Taken together, these factors indicate that the meme coin exhibits good farming potential.", '
            '"good_farming": true}'
        ),
    },
    # Farming with creator-funded bundle
    {
        "role": "user",
        "content": [
            {
                "type": "text",
                "text": (
                    "Creator-funded Bundle: Yes\n"
                    "Creator-funded Buy Bundle: No\n"
                    "Buy Bundle: Low\n"
                    "Sell Bundle: Low\n"
                    "Pre-migration Duration: High\n"
                    "Number of Unique Traders: High\n"
                    "Number of Transactions: High\n"
                    "Holding Centralization: High\n"
                    "Comment History:\n"
                    "7tPtnG: 2X IS NOT ENOUGH?\n"
                    "8PKg9x: $TRUMPAI INVEST BEFORE IT GOES 100X\n"
                    "Does this meme coin have good farming potential?"
                ),
            },
            {
                "type": "image_url",
                "image_url": {
                    "url": IMAGE_URL_TEMP.format(
                        ca="6QXbUVM4KmpLuFvUWP3mrTqVB4nn1idfK1PdXQaYqycv"
                    ),
                    "detail": "high",
                },
            },
        ],
    },
    {
        "role": "assistant",
        "content": (
            '{"reasoning": "First, the candlestick chart shows a medium pre-migration duration, indicating some level of community engagement. '
            "Second, this meme coin involves a creator-funded bundle, indicating the creator accumulated a significant share of tokens before migration. "
            "Such behavior often signals an intent to dump post-migration, which undermines the coin's sustainability. "
            'Despite favorable candlestick chart, transaction indicators, and comment history, the presence of a creator-funded bundle strongly suggests poor farming potential.", '
            '"good_farming": false}'
        ),
    },
    # Farming with high buy bundle
    {
        "role": "user",
        "content": [
            {
                "type": "text",
                "text": (
                    "Creator-funded Bundle: No\n"
                    "Creator-funded Buy Bundle: No\n"
                    "Buy Bundle: High\n"
                    "Sell Bundle: Low\n"
                    "Pre-migration Duration: High\n"
                    "Number of Unique Traders: High\n"
                    "Number of Transactions: High\n"
                    "Holding Centralization: Low\n"
                    "Comment History:\n"
                    "\n"
                    "Does this meme coin have good farming potential?"
                ),
            },
            {
                "type": "image_url",
                "image_url": {
                    "url": IMAGE_URL_TEMP.format(
                        ca="Fk1ccWiNwNUCrtBRCKHn2Wwg7UEiXc8mN3TkRAmBpump"
                    ),
                    "detail": "high",
                },
            },
        ],
    },
    {
        "role": "assistant",
        "content": (
            '{"reasoning": "First, the candlestick chart shows a healthy pre-migration duration with multiple price fluctuations, indicating active trading activity. '
            "Second, the meme coin lacks both a creator-funded bundle and a creator-funded buy bundle, suggesting that the creator is not manipulating the market. "
            "Third, this meme coin has a high buy bundle, indicating significant bot activity. "
            "While the pre-migration duration, number of unique traders, and number of transactions are all high, "
            "the presence of a high buy bundle suggests that the coin is likely to experience a price spike followed by a decline. "
            'These factors suggest that the meme coin exhibits poor farming potential.", '
            '"good_farming": false}'
        ),
    },
    # Low pre-migration duration, traders, and transactions
    {
        "role": "user",
        "content": [
            {
                "type": "text",
                "text": (
                    "Creator-funded Bundle: No\n"
                    "Creator-funded Buy Bundle: No\n"
                    "Buy Bundle: Medium\n"
                    "Sell Bundle: Medium\n"
                    "Pre-migration Duration: Low\n"
                    "Number of Unique Traders: Low\n"
                    "Number of Transactions: Low\n"
                    "Holding Centralization: Medium\n"
                    "Comment History:\n"
                    "\n"
                    "Does this meme coin have good farming potential?"
                ),
            },
            {
                "type": "image_url",
                "image_url": {
                    "url": IMAGE_URL_TEMP.format(
                        ca="ALQ2KGVhUJVtvZRvito6wu4rrCfqinZsc9Uwp9jvpump"
                    ),
                    "detail": "high",
                },
            },
        ],
    },
    {
        "role": "assistant",
        "content": (
            '{"reasoning": "First, the candlestick chart shows a healthy pre-migration duration with multiple price fluctuations, indicating active trading activity. '
            "Second, the meme coin lacks both a creator-funded bundle and a creator-funded buy bundle, suggesting that the creator is not manipulating the market. "
            "Third, the buy bundle and sell bundle are both at a moderate level, pointing to medium bot activity. "
            "Fourth, the low pre-migration duration, low number of unique traders, and low transaction number all indicate limited community engagement and activity. "
            "Fifth, the medium holding centralization suggests that a moderate number of holders control a significant portion of the tokens, which is often a sign of poor distribution. "
            "Finally, there is no comment history, indicating a lack of community interaction. "
            'Taken together, these factors strongly suggest that the meme coin does not exhibit good farming potential.", '
            '"good_farming": false}'
        ),
    },
]

PROMPT_COIN_AGENT = (
    "Creator-funded Bundle: {creator_funded_bundle}\n"
    "Creator-funded Buy Bundle: {creator_funded_buy_bundle}\n"
    "Buy Bundle: {buy_bundle}\n"
    "Sell Bundle: {sell_bundle}\n"
    "Pre-migration Duration: {pre_migration_duration}\n"
    "Number of Unique Traders: {number_of_unique_traders}\n"
    "Number of Transactions: {number_of_transactions}\n"
    "Holding Centralization: {holding_centralization}\n"
    "Comment History:\n"
    "{comment_history}\n"
    "Does this meme coin have good farming potential?"
)
